import pytest
from app.services import hitl_service
from app.models.db import CommandMapping, TrainingExample
from app.schemas import MappingReviewIn

@pytest.fixture
def mock_embedding(monkeypatch):
    from app.services import vector_search
    monkeypatch.setattr(vector_search, "embed_text", lambda text: [0.0] * 384)

@pytest.mark.asyncio
async def test_hitl_loop1_rag_redacts_and_embeds(mock_embedding, monkeypatch, tmp_path):
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/test.db")
    from app.db import SessionLocal, Base, engine
    Base.metadata.create_all(bind=engine)
    db_session = SessionLocal()

    from app.models.db import Tenant, CommandMapping, TrainingExample
    import uuid
    test_tenant = Tenant(name=f"TestTenant_{uuid.uuid4()}")
    db_session.add(test_tenant)
    db_session.commit()

    # 1. Simulate an unknown command mapping generated by the pipeline
    mapping = CommandMapping(
        tenant_id=test_tenant.id,
        vendor="cisco",
        raw_command_pattern="snmp-server community SUPER_SECRET123 RO",
        normalized_parameter="extra_parameters.unknown_evidence",
        ai_suggested_meaning="SNMP community string",
        confidence=0.4,
        status="pending"
    )
    db_session.add(mapping)
    db_session.commit()

    # 2. Human reviewer corrects the mapping
    from app.schemas import MappingReviewIn
    review = MappingReviewIn(
        action="correct",
        normalized_facts={"facts": [{"parameter": "snmp.community_strings", "expected": True, "actual": "SUPER_SECRET123"}]},
        correction_reason="Map it to the SNMP model list"
    )

    from app.services import hitl_service
    mock_user = type("User", (), {"username": "admin_user"})
    hitl_service.correct_mapping(
        db_session, mapping, review.normalized_facts, review.correction_reason, mock_user
    )

    # 3. Verify the CommandMapping is approved
    db_session.refresh(mapping)
    assert mapping.status == "approved"

    # 4. Verify TrainingExample is created with redacted secret
    example = db_session.query(TrainingExample).filter_by(source_mapping_id=mapping.id).first()
    assert example is not None
    assert example.human_action == "CORRECTED"
    assert example.correction_reason == "Map it to the SNMP model list"
    assert example.raw_config_redacted == "snmp-server community ********* RO"
    
    # 5. Verify the updated mapping has an embedding generated for RAG
    assert mapping.embedding is not None
