"""initial schema

Revision ID: 0cecc91f91a6
Revises: 
Create Date: 2026-09-03 11:14:35.323284

"""
from alembic import op
import sqlalchemy as sa


revision = '0cecc91f91a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('raw_command_pattern', sa.Text(), nullable=True),
    sa.Column('normalized_parameter', sa.String(), nullable=True),
    sa.Column('example_value', sa.String(), nullable=True),
    sa.Column('ai_suggested_meaning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_compliance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('raw_config_path', sa.String(), nullable=True),
    sa.Column('raw_config_hash', sa.String(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('baseline_json', sa.JSON(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('opa_decision', sa.String(), nullable=True),
    sa.Column('opa_policy_version', sa.String(), nullable=True),
    sa.Column('opa_decision_id', sa.String(), nullable=True),
    sa.Column('batfish_status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('final_reason', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batfish_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('network_name', sa.String(), nullable=True),
    sa.Column('snapshot_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('critical_violation', sa.Boolean(), nullable=True),
    sa.Column('init_issues', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=False),
    sa.Column('opa_decision_id', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.Column('fabric_status', sa.String(), nullable=True),
    sa.Column('fabric_tx_id', sa.String(), nullable=True),
    sa.Column('fabric_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('control_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('expected_value', sa.String(), nullable=True),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('evidence_line', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opa_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opa_analyses')
    op.drop_table('findings')
    op.drop_table('evidence_records')
    op.drop_table('batfish_analyses')
    op.drop_table('scans')
    op.drop_table('devices')
    op.drop_table('tenants')
    op.drop_table('command_mappings')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
