"""Add Gns3Server table

Revision ID: 17135e725e5f
Revises: 3e117b3e0a3d
Create Date: 2026-09-07 23:59:35.964005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '17135e725e5f'
down_revision = '3e117b3e0a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gns3_servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('initialized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gns3_servers_created_at'), 'gns3_servers', ['created_at'], unique=False)
    op.create_index(op.f('ix_gns3_servers_tenant_id'), 'gns3_servers', ['tenant_id'], unique=False)
    op.drop_index('ix_golden_configs_device_id', table_name='golden_configs')
    op.drop_table('golden_configs')
    op.drop_index('ix_compliance_baselines_device_role', table_name='compliance_baselines')
    op.drop_table('compliance_baselines')
    op.drop_index('ix_config_drifts_detected_at', table_name='config_drifts')
    op.drop_index('ix_config_drifts_device_id', table_name='config_drifts')
    op.drop_table('config_drifts')
    op.drop_column('training_jobs', 'artifact_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('artifact_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('config_drifts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('baseline', postgresql.ENUM('GOLDEN_CONFIG', 'PREVIOUS_BACKUP', 'ROLE_BASELINE', name='driftbaseline'), autoincrement=False, nullable=False),
    sa.Column('diff_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_lines', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('removed_lines', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_lines', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('compliance_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='driftseverity'), autoincrement=False, nullable=False),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cli_diff', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'APPROVED', 'ROLLED_BACK', 'DISMISSED', name='driftstatus'), autoincrement=False, nullable=False),
    sa.Column('maintenance_window_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unattributed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='config_drifts_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='config_drifts_pkey')
    )
    op.create_index('ix_config_drifts_device_id', 'config_drifts', ['device_id'], unique=False)
    op.create_index('ix_config_drifts_detected_at', 'config_drifts', ['detected_at'], unique=False)
    op.create_table('compliance_baselines',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('set_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='compliance_baselines_pkey')
    )
    op.create_index('ix_compliance_baselines_device_role', 'compliance_baselines', ['device_role'], unique=True)
    op.create_table('golden_configs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('set_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='golden_configs_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='golden_configs_pkey')
    )
    op.create_index('ix_golden_configs_device_id', 'golden_configs', ['device_id'], unique=True)
    op.drop_index(op.f('ix_gns3_servers_tenant_id'), table_name='gns3_servers')
    op.drop_index(op.f('ix_gns3_servers_created_at'), table_name='gns3_servers')
    op.drop_table('gns3_servers')
    # ### end Alembic commands ###
