"""add config drift feature models

Revision ID: 3e117b3e0a3d
Revises: o0p1q2r3s4t5
Create Date: 2026-09-07 14:29:56.238053

"""
from alembic import op
import sqlalchemy as sa


revision = '3e117b3e0a3d'
down_revision = 'o0p1q2r3s4t5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_role', sa.String(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('set_by', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_baselines_device_role'), 'compliance_baselines', ['device_role'], unique=True)
    op.create_table('config_drifts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('baseline', sa.Enum('GOLDEN_CONFIG', 'PREVIOUS_BACKUP', 'ROLE_BASELINE', name='driftbaseline'), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('added_lines', sa.Integer(), nullable=False),
    sa.Column('removed_lines', sa.Integer(), nullable=False),
    sa.Column('modified_lines', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='driftseverity'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('cli_diff', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'APPROVED', 'ROLLED_BACK', 'DISMISSED', name='driftstatus'), nullable=False),
    sa.Column('maintenance_window_id', sa.String(), nullable=True),
    sa.Column('unattributed', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_drifts_detected_at'), 'config_drifts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_config_drifts_device_id'), 'config_drifts', ['device_id'], unique=False)
    op.create_table('golden_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('set_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_configs_device_id'), 'golden_configs', ['device_id'], unique=True)
    op.drop_index('ix_ai_analyses_scan_id', table_name='ai_analyses')
    op.create_foreign_key(None, 'audit_log', 'tenants', ['tenant_id'], ['id'])
    # NOTE: change_requests.snapshot_diff is NOT added here -- it already
    # exists by this point in the chain (added by revision n9o0p1q2r3s4,
    # an ancestor of this migration). The original autogenerated
    # `op.add_column('change_requests', sa.Column('snapshot_diff', ...))`
    # here was a duplicate (DuplicateColumn on a clean `alembic upgrade
    # head`) left over from autogenerating this migration against a
    # branch that hadn't merged n9o0p1q2r3s4 yet.
    op.drop_index('ix_command_mappings_embedding_cosine', table_name='command_mappings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_foreign_key(None, 'command_mappings', 'tenants', ['tenant_id'], ['id'])
    op.add_column('training_jobs', sa.Column('artifact_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'artifact_hash')
    op.drop_constraint(None, 'command_mappings', type_='foreignkey')
    op.create_index('ix_command_mappings_embedding_cosine', 'command_mappings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_index('ix_ai_analyses_scan_id', 'ai_analyses', ['scan_id'], unique=False)
    op.drop_index(op.f('ix_golden_configs_device_id'), table_name='golden_configs')
    op.drop_table('golden_configs')
    op.drop_index(op.f('ix_config_drifts_device_id'), table_name='config_drifts')
    op.drop_index(op.f('ix_config_drifts_detected_at'), table_name='config_drifts')
    op.drop_table('config_drifts')
    op.drop_index(op.f('ix_compliance_baselines_device_role'), table_name='compliance_baselines')
    op.drop_table('compliance_baselines')
    # ### end Alembic commands ###